#!/usr/bin/env python3
"""Generate sessions/INDEX.md — reverse-chronological index of all session logs.

Run standalone or called from the digest workflow alongside refresh_digest.py.
Handles both YAML-frontmatter and heading-based session log formats.
"""
import glob
import os
import re

SESSIONS_DIR = "sessions"
OUTPUT = os.path.join(SESSIONS_DIR, "INDEX.md")


def parse_session(path):
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read(2000)
    except OSError:
        return None

    title = ""
    date = ""

    for line in content.splitlines():
        if line.startswith("title:"):
            title = line[6:].strip().strip('"').strip("'")
        elif line.startswith("date:"):
            date = line[5:].strip().strip('"').strip("'")
        if title and date:
            break

    if not (title and date):
        for line in content.splitlines():
            if not line.startswith("#"):
                continue
            text = line.lstrip("#").strip()
            if text.lower().startswith("session "):
                text = text[8:].strip()
            m = re.match(r"(\d{4}-\d{2}-\d{2})\s*[—–-]+\s*(.+)", text)
            if m:
                date = m.group(1)
                title = m.group(2).strip()
                break

    if not date:
        fn = os.path.basename(path)
        m = re.match(r"(\d{4}-\d{2}-\d{2})", fn)
        if m:
            date = m.group(1)

    if not date:
        return None

    if not title:
        title = os.path.basename(path).replace(".md", "")

    return {"date": date, "title": title, "path": path.replace("\\", "/")}


def main():
    files = sorted(glob.glob(f"{SESSIONS_DIR}/*.md"), reverse=True)
    files = [f for f in files if os.path.basename(f) != "INDEX.md"]

    sessions = []
    for path in files:
        s = parse_session(path)
        if s:
            sessions.append(s)

    sessions.sort(key=lambda x: x["date"], reverse=True)

    lines = [
        "# Session Index",
        f"_{len(sessions)} logs · reverse-chronological · auto-generated_",
        "",
        "| Date | Session |",
        "|------|---------|",
    ]
    for s in sessions:
        link = f"[{s['title']}]({s['path']})"
        lines.append(f"| {s['date']} | {link} |")
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/generate_session_index.py` · "
        "updated on every digest refresh_"
    )
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"sessions/INDEX.md written — {len(sessions)} sessions indexed")


if __name__ == "__main__":
    main()
