#!/usr/bin/env python3
"""
F5's one kept promotion-guard rule (ops/pending.md, 2026-07-12, carried over
from the dropped claims-ledger design): "an agent may not mark its own claim
verified." suite-state.md's Product Pulse table (F4) is the one place a
signal's current value gets asserted as live fact -- every row there must
come from refresh_suite_state.py's own nightly run, never a hand or agent
edit inside a PR.

The bot itself never opens a PR -- both Refresher workflows push straight to
main (see .github/workflows/{suite-state,digest}-refresh.yml's "Commit if
changed" step). So this only needs to ask one question: did this PR change
any Product Pulse row's value versus the PR's base? If yes, that is, by
construction, exactly the case this guard exists to catch.

Run in CI, pull_request context only (see .github/workflows/md-health.yml):
  python scripts/pulse_promotion_guard.py <base-sha-or-ref>
"""
import re
import subprocess
import sys


def extract_pulse_rows(content):
    """{row_label: value_cell} for every data row in the Product Pulse table.
    Pure function -- no I/O. Returns {} if the section doesn't exist yet
    (e.g. a repo/branch that predates this feature)."""
    m = re.search(r"## Product Pulse.*?\n\n(.*?)\n\n", content, flags=re.DOTALL)
    if not m:
        return {}
    rows = {}
    for line in m.group(1).splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        label = cells[0]
        if not label or label == "Signal" or set(label) == {"-"}:
            continue
        rows[label] = cells[1]
    return rows


def hand_edited_rows(before_content, after_content):
    """Row labels whose value cell differs between before/after. A brand-new
    row (not in `before`) counts too -- the guard is "the bot wrote this
    value", and a PR introducing a never-computed row fails that the same way
    a changed one does. Pure function."""
    before = extract_pulse_rows(before_content)
    after = extract_pulse_rows(after_content)
    return [label for label, val in after.items() if before.get(label) != val]


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: pulse_promotion_guard.py <base-sha-or-ref>", file=sys.stderr)
        sys.exit(2)
    base = sys.argv[1]

    before_proc = subprocess.run(
        ["git", "show", f"{base}:suite-state.md"],
        capture_output=True, text=True,
    )
    # A missing file at base (e.g. this PR adds suite-state.md itself, or the
    # base predates the Product Pulse feature) is not a violation -- empty
    # `before` just means every row in `after` is "new", which the diff
    # against a real prior value would already have flagged if one existed.
    before_content = before_proc.stdout if before_proc.returncode == 0 else ""

    with open("suite-state.md", encoding="utf-8") as f:
        after_content = f.read()

    hits = hand_edited_rows(before_content, after_content)
    if hits:
        print(
            "::error::This PR changes suite-state.md's Product Pulse row(s): "
            + ", ".join(hits)
            + ". Every value there is machine-generated by refresh_suite_state.py's "
              "nightly run (system/failures.md F4) -- per the kept promotion-guard rule "
              "(ops/pending.md, 2026-07-12), a PR may not assert its own value there. "
              "Revert this hunk; if the signal itself is wrong, fix "
              ".github/scripts/refresh_suite_state.py instead and let the next nightly "
              "run (or a workflow_dispatch) produce the real value."
        )
        sys.exit(1)

    print("Product Pulse section: no hand-edited rows in this PR — OK.")
